'use client'

import { useState } from 'react'
import { Info, X } from 'lucide-react'
import { SCORE_THRESHOLDS } from '@/lib/scores'

export default function ScoringMethodologyModal() {
  const [open, setOpen] = useState(false)

  const dimensions = [
    { name: 'Overall Score', weight: 'Weighted avg', desc: 'Composite score favoring ecosystem completeness and moat strength. Primary ranking metric.' },
    { name: 'Sentiment', weight: 'Social signals', desc: 'X/Twitter sentiment analysis — bullish/bearish signal strength from recent posts mentioning key tickers and theme keywords.' },
    { name: 'Ecosystem', weight: 'Completeness', desc: 'How complete and well-connected the value chain is. More members with clear roles = higher score.' },
    { name: 'Risk', weight: 'External factors', desc: 'Assessment of regulatory, competitive, and macro risks. Lower risk = higher score.' },
    { name: 'Opportunity', weight: 'Bottlenecks', desc: 'Pricing power and bottleneck analysis. Companies with strong pricing power in bottlenecks score higher.' },
    { name: 'Moat', weight: 'Valuation', weight2: '1-10 scale', desc: 'Competitive moat strength of top picks. Wide moats (like network effects, switching costs) score highest.' },
  ]

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
      >
        <Info className="w-3.5 h-3.5" />
        How are scores calculated?
      </button>

      {open && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
          onClick={() => setOpen(false)}
        >
          <div
            className="bg-card border border-border rounded-2xl max-w-lg w-full max-h-[80vh] overflow-y-auto p-6"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-display text-lg font-bold">Scoring Methodology</h2>
              <button onClick={() => setOpen(false)} className="p-1 hover:bg-muted rounded-lg transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>

            <p className="text-sm text-muted-foreground mb-4">
              ThemeInvestor analyzes investment themes across 6 dimensions, each scored 0–100. Scores are generated by AI
              analysis of your thesis text, ecosystem mapping, and live social media sentiment from X/Twitter.
            </p>

            {/* Color legend */}
            <div className="flex items-center gap-4 mb-6 p-3 bg-muted/50 rounded-lg">
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-success" />
                <span className="text-xs font-medium">Strong ({SCORE_THRESHOLDS.strong}+)</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-yellow-500" />
                <span className="text-xs font-medium">Moderate ({SCORE_THRESHOLDS.moderate}–{SCORE_THRESHOLDS.strong - 1})</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-red-500" />
                <span className="text-xs font-medium">Weak (&lt;{SCORE_THRESHOLDS.moderate})</span>
              </div>
            </div>

            {/* Dimensions */}
            <div className="space-y-3">
              {dimensions.map(d => (
                <div key={d.name} className="border-b border-border/50 pb-3 last:border-0">
                  <div className="flex items-center gap-2 mb-1">
                    <h3 className="font-medium text-sm">{d.name}</h3>
                    <span className="text-xs px-2 py-0.5 bg-primary/10 text-primary rounded-full">{d.weight}</span>
                    {d.weight2 && (
                      <span className="text-xs px-2 py-0.5 bg-muted text-muted-foreground rounded-full">{d.weight2}</span>
                    )}
                  </div>
                  <p className="text-xs text-muted-foreground leading-relaxed">{d.desc}</p>
                </div>
              ))}
            </div>

            <div className="mt-4 p-3 bg-muted/30 rounded-lg">
              <p className="text-xs text-muted-foreground">
                💡 <strong>Tip:</strong> Scores reflect the AI&apos;s assessment based on available data. Always do your own
                research before investing. Paper trading lets you test strategies risk-free.
              </p>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
